### ISSUE TITLE
Automatically categorizing 3D models (clustering)

### ISSUE THREAD

**Issue by Jip-Hop** [ascribe/match3d#5]
Hi,

I'd like to automatically cluster a few hundred 3D models in a few categories (let's say 5). The categories are not predefined. I will specify them after manually inspecting the clusters. Since match3d is able to score the similarly between models I thought I could somehow use match3d to cluster my models. Do you have an idea how I could do this?

**Comment by rhsimplex** [comment]
Hi @Jip-Hop, thanks for the question and sorry I haven't been maintaining this repository.

You could use match3d for pairwise similarity, but be aware that models that are more than a little different will all have similarly high scores -- there's a really sharp upward curve in the similarity score when the models are any more than a little different.

Also, the underlying image-match is several versions ahead and has been moved to python3.  So you may have to use an old version.

**Comment by Jip-Hop** [comment]
Thanks for replying! But it sounds like I should take a different approach then. May look into it again another time.
